# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mvrnormArma <- function(mu, sigma) {
    .Call('_rcppFastAlternatives_mvrnormArma', PACKAGE = 'rcppFastAlternatives', mu, sigma)
}

